### ISSUE TITLE
Missing file and non-existing folder

### ISSUE THREAD

**Issue by IQBigBang** [Mohamed-94/Mega-Number#3]
Hi,
I like your project, so I cloned __master__ branch and tried to open project in MonoDevelop.
When I opened [MegaNumber.sln](https://github.com/Mohamed-94/Mega-Number/blob/master/MegaNumber.sln), error showed up:
`/Mega-Number/Super_Calcilator/MegaNumber.csproj not found`
On line 6 (in MegaNumber.sln), you refer to _Super_Calcilator_ folder that does not exist.

When I repaired that, project was succesfully opened, but MonoDevelop is missing Form.cs file. When I'm trying to build the project, it says that _Form1_ is undefinded.
Just sayin'...

**Comment by Mohamed-94** [comment]
Hi, IQBigBang..
Thank you for this great issue, i have checked that out ..,You just need to find MegaNumber.cs file and then rename it to Form1.cs .
I have also correct that in the main repository-(if you tend to clone it again.!)
tell me if that work>!
Thank you again for your interest.
